### PR TITLE
scala 2.13 support

### PR DESCRIPTION
**Pull request by danbills**
* removed some deprecated compiler flags
* tut is deprecated, migrated to mdoc

### CODE REVIEW

**Comment by Tvaroh** [comment]
Looks great, thank you @danbills!

**Comment by danbills** [comment]
thanks for merging, could you please publish?  Or is that done automagically?

**Comment by 23will** [comment]
@danbills I was a bit hasty on merging, turns out the tests and mdoc compiliation weren't working. Addressed some of the issues in branch `fix-mdoc-compilation` but still need to fix the mdoc README.md as the code in it doesn't compile. Once fixed, I will publish

**Comment by danbills** [comment]
@23will sorry for missing the tests, I pushed a a fix for that [here](https://github.com/RMSone/slick-cats/pull/49).

I looked at the mdoc issue and I wasn't able to immediately figure out why it wasn't producing output even when configured correctly.

**Pull request merged**
